<a href="https://colab.research.google.com/github/aneeshsunganahalli/PyTorchRef/blob/main/PyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("PyTorch")

PyTorch


In [ ]:
!nvidia-smi

Fri Mar 28 10:14:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   65C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Tensors

### Creating Tensors


In [ ]:
# Scalar
scalar = torch.tensor(9)
scalar

tensor(9)

In [ ]:
scalar.ndim

0

In [ ]:
# Vector
vector = torch.tensor([9,2])
vector

tensor([9, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[4,7],[9,2]])
matrix

tensor([[4, 7],
        [9, 2]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
Tensor
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
### Random Tensors
randomTensor = torch.rand(1,3,5)
randomTensor

tensor([[[0.2017, 0.9435, 0.7334, 0.2620, 0.6149],
         [0.2610, 0.1797, 0.5974, 0.9762, 0.5808],
         [0.1638, 0.8030, 0.6249, 0.5620, 0.8252]]])

In [ ]:
randomTensor.ndim

3

In [ ]:
# Tensor with similar shape to image tensor
randomImageSizeTensor = torch.rand(size=(3,224,224))
randomImageSizeTensor.ndim, randomImageSizeTensor.shape

(3, torch.Size([3, 224, 224]))